org.gradle.java.home=/usr/lib/jvm/java-21-openjdk
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
org.gradle.daemon.performance.disable-logging=true
org.gradle.parallel=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.6
loom_version=1.16-SNAPSHOT
fabric_api_version=0.141.3+1.21.11

mod_version=1.4.3
maven_group=name.radik
archives_base_name=radik
