package com.radik.block;

import com.radik.Radik;
import com.radik.RadikCore;
import com.radik.block.custom.*;
import net.minecraft.block.*;
import net.minecraft.block.entity.BlockEntityType;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.BlockSoundGroup;
import net.minecraft.util.Identifier;
import org.jetbrains.annotations.NotNull;


public class RegisterBlocks {

    public static final Block FROG0_255_0 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog0_255_0");
    public static final Block FROG0_255_255 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog0_255_255");
    public static final Block FROG96_51_0 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog96_51_0");
    public static final Block FROG255_0_0 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog255_0_0");
    public static final Block FROG255_0_255 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog255_0_255");
    public static final Block FROG255_255_255 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog255_255_255");
    public static final Block FROG255_0_0R = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog255_0_0r");
    public static final Block FROG0_0_0 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog0_0_0");
    public static final Block FROG50_50_50 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog50_50_50");
    public static final Block FROG100_100_100 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog100_100_100");
    public static final Block FROG255_100_0 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog255_100_0");
    public static final Block FROG0_0_255 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog0_0_255");
    public static final Block FROG100_100_255 = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.OCHRE_FROGLIGHT)), "frog100_100_255");



    public static final Block BRICK1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick1");
    public static final Block BRICK2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick2");
    public static final Block BRICK3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick3");
    public static final Block BRICK4 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick4");
    public static final Block BRICK5 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick5");
    public static final Block BRICK6 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick6");
    public static final Block BRICK7 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick7");
    public static final Block BRICK8 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick8");
    public static final Block BRICK9 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick9");
    public static final Block BRICK10 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick10");
    public static final Block BRICK11 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick11");
    public static final Block BRICK12 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick12");
    public static final Block BRICK13 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick13");
    public static final Block BRICK14 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick14");
    public static final Block BRICK15 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick15");
    public static final Block BRICK16 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick16");
    public static final Block BRICK_STAIR1 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair1");
    public static final Block BRICK_STAIR2 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair2");
    public static final Block BRICK_STAIR3 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair3");
    public static final Block BRICK_STAIR4 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair4");
    public static final Block BRICK_STAIR5 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair5");
    public static final Block BRICK_STAIR6 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair6");
    public static final Block BRICK_STAIR7 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair7");
    public static final Block BRICK_STAIR8 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair8");
    public static final Block BRICK_STAIR9 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair9");
    public static final Block BRICK_STAIR10 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair10");
    public static final Block BRICK_STAIR11 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair11");
    public static final Block BRICK_STAIR12 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair12");
    public static final Block BRICK_STAIR13 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair13");
    public static final Block BRICK_STAIR14 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair14");
    public static final Block BRICK_STAIR15 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair15");
    public static final Block BRICK_STAIR16 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_stair16");
    public static final Block BRICK_SLAB1 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab1");
    public static final Block BRICK_SLAB2 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab2");
    public static final Block BRICK_SLAB3 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab3");
    public static final Block BRICK_SLAB4 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab4");
    public static final Block BRICK_SLAB5 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab5");
    public static final Block BRICK_SLAB6 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab6");
    public static final Block BRICK_SLAB7 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab7");
    public static final Block BRICK_SLAB8 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab8");
    public static final Block BRICK_SLAB9 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab9");
    public static final Block BRICK_SLAB10 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab10");
    public static final Block BRICK_SLAB11 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab11");
    public static final Block BRICK_SLAB12 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab12");
    public static final Block BRICK_SLAB13 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab13");
    public static final Block BRICK_SLAB14 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab14");
    public static final Block BRICK_SLAB15 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab15");
    public static final Block BRICK_SLAB16 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_slab16");
    public static final Block BRICK_WALL1 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall1");
    public static final Block BRICK_WALL2 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall2");
    public static final Block BRICK_WALL3 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall3");
    public static final Block BRICK_WALL4 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall4");
    public static final Block BRICK_WALL5 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall5");
    public static final Block BRICK_WALL6 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall6");
    public static final Block BRICK_WALL7 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall7");
    public static final Block BRICK_WALL8 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall8");
    public static final Block BRICK_WALL9 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall9");
    public static final Block BRICK_WALL10 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall10");
    public static final Block BRICK_WALL11 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall11");
    public static final Block BRICK_WALL12 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall12");
    public static final Block BRICK_WALL13 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall13");
    public static final Block BRICK_WALL14 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall14");
    public static final Block BRICK_WALL15 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall15");
    public static final Block BRICK_WALL16 = registerBlock(new WallBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_wall16");



    public static final Block BRICK_ARRAY_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_1");
    public static final Block BRICK_ARRAY_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_2");
    public static final Block BRICK_ARRAY_3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_3");
    public static final Block BRICK_ARRAY_4 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_4");
    public static final Block BRICK_ARRAY_5 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_5");
    public static final Block BRICK_ARRAY_6 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_6");
    public static final Block BRICK_ARRAY_7 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_7");
    public static final Block BRICK_ARRAY_8 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_8");
    public static final Block BRICK_ARRAY_9 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_9");
    public static final Block BRICK_ARRAY_10 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_10");
    public static final Block BRICK_ARRAY_11 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_11");
    public static final Block BRICK_ARRAY_12 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_12");
    public static final Block BRICK_ARRAY_13 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_13");
    public static final Block BRICK_ARRAY_14 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_14");
    public static final Block BRICK_ARRAY_15 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_15");
    public static final Block BRICK_ARRAY_16 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_16");
    public static final Block BRICK_ARRAY_17 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_17");
    public static final Block BRICK_ARRAY_18 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_18");
    public static final Block BRICK_ARRAY_19 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_19");
    public static final Block BRICK_ARRAY_20 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_20");
    public static final Block BRICK_ARRAY_21 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "brick_array_21");

    public static final Block BEVEL_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "bevel_1");
    public static final Block BEVEL_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "bevel_2");
    public static final Block BISMUTH_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DIAMOND_BLOCK)), "bismuth_1");
    public static final Block BISMUTH_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.EMERALD_BLOCK)), "bismuth_2");
    public static final Block BISMUTH_3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.GLOWSTONE)), "bismuth_3");

    public static final Block BRAID_STAIR_1 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_stair_1");
    public static final Block BRAID_STAIR_2 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_stair_2");
    public static final Block BRAID_STAIR_3 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_stair_3");
    public static final Block BRAID_STAIR_4 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_stair_4");
    public static final Block BRAID_STAIR_5 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_stair_5");
    public static final Block BRAID_STAIR_6 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_stair_6");
    public static final Block BRAID_STAIR_7 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_stair_7");
    public static final Block BRAID_STAIR_101 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_stair_101");
    public static final Block BRAID_STAIR_102 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_stair_102");
    public static final Block BRAID_STAIR_103 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_stair_103");
    public static final Block BRAID_STAIR_104 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_stair_104");
    public static final Block BRAID_STAIR_105 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_stair_105");
    public static final Block BRAID_STAIR_106 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.QUARTZ_BLOCK)), "braid_stair_106");
    public static final Block BRAID_STAIR_107 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.PACKED_ICE)), "braid_stair_107");
    public static final Block BRAID_STAIR_108 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.GLOWSTONE).dropsLike(Blocks.GLOWSTONE)), "braid_stair_108");
    public static final Block BRAID_STAIR_109 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.END_STONE)), "braid_stair_109");
    public static final Block BRAID_STAIR_110 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.DEEPSLATE)), "braid_stair_110");
    public static final Block BRAID_STAIR_111 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.COBBLESTONE)), "braid_stair_111");
    public static final Block BRAID_STAIR_112 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.COAL_BLOCK)), "braid_stair_112");
    public static final Block BRAID_STAIR_113 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.PRISMARINE)), "braid_stair_113");
    public static final Block BRAID_STAIR_114 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.REDSTONE_BLOCK)), "braid_stair_114");
    public static final Block BRAID_STAIR_115 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "braid_stair_115");
    public static final Block BRAID_STAIR_116 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "braid_stair_116");
    public static final Block BRAID_STAIR_117 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BRICKS)), "braid_stair_117");
    public static final Block BRAID_STAIR_201 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_201");
    public static final Block BRAID_STAIR_202 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_202");
    public static final Block BRAID_STAIR_203 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_203");
    public static final Block BRAID_STAIR_204 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_204");
    public static final Block BRAID_STAIR_205 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_205");
    public static final Block BRAID_STAIR_206 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_206");
    public static final Block BRAID_STAIR_207 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_207");
    public static final Block BRAID_STAIR_208 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_208");
    public static final Block BRAID_STAIR_209 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_209");
    public static final Block BRAID_STAIR_210 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_210");
    public static final Block BRAID_STAIR_211 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_211");
    public static final Block BRAID_STAIR_212 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_212");
    public static final Block BRAID_STAIR_213 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_213");
    public static final Block BRAID_STAIR_214 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_214");
    public static final Block BRAID_STAIR_215 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_215");
    public static final Block BRAID_STAIR_216 = registerBlock(new StairsBlock(Blocks.BRICK_STAIRS.getDefaultState(), AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_stair_216");
    public static final Block BRAID_SLAB_1 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_slab_1");
    public static final Block BRAID_SLAB_2 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_slab_2");
    public static final Block BRAID_SLAB_3 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_slab_3");
    public static final Block BRAID_SLAB_4 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_slab_4");
    public static final Block BRAID_SLAB_5 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_slab_5");
    public static final Block BRAID_SLAB_6 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_slab_6");
    public static final Block BRAID_SLAB_7 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_slab_7");
    public static final Block BRAID_SLAB_101 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_slab_101");
    public static final Block BRAID_SLAB_102 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_slab_102");
    public static final Block BRAID_SLAB_103 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_slab_103");
    public static final Block BRAID_SLAB_104 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_slab_104");
    public static final Block BRAID_SLAB_105 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_slab_105");
    public static final Block BRAID_SLAB_106 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.QUARTZ_BLOCK)), "braid_slab_106");
    public static final Block BRAID_SLAB_107 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.PACKED_ICE)), "braid_slab_107");
    public static final Block BRAID_SLAB_108 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.GLOWSTONE).dropsLike(Blocks.GLOWSTONE)), "braid_slab_108");
    public static final Block BRAID_SLAB_109 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.END_STONE)), "braid_slab_109");
    public static final Block BRAID_SLAB_110 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.DEEPSLATE)), "braid_slab_110");
    public static final Block BRAID_SLAB_111 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.COBBLESTONE)), "braid_slab_111");
    public static final Block BRAID_SLAB_112 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.COAL_BLOCK)), "braid_slab_112");
    public static final Block BRAID_SLAB_113 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.PRISMARINE)), "braid_slab_113");
    public static final Block BRAID_SLAB_114 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.REDSTONE_BLOCK)), "braid_slab_114");
    public static final Block BRAID_SLAB_115 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "braid_slab_115");
    public static final Block BRAID_SLAB_116 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "braid_slab_116");
    public static final Block BRAID_SLAB_117 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BRICKS)), "braid_slab_117");
    public static final Block BRAID_SLAB_201 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_201");
    public static final Block BRAID_SLAB_202 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_202");
    public static final Block BRAID_SLAB_203 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_203");
    public static final Block BRAID_SLAB_204 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_204");
    public static final Block BRAID_SLAB_205 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_205");
    public static final Block BRAID_SLAB_206 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_206");
    public static final Block BRAID_SLAB_207 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_207");
    public static final Block BRAID_SLAB_208 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_208");
    public static final Block BRAID_SLAB_209 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_209");
    public static final Block BRAID_SLAB_210 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_210");
    public static final Block BRAID_SLAB_211 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_211");
    public static final Block BRAID_SLAB_212 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_212");
    public static final Block BRAID_SLAB_213 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_213");
    public static final Block BRAID_SLAB_214 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_214");
    public static final Block BRAID_SLAB_215 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_215");
    public static final Block BRAID_SLAB_216 = registerBlock(new SlabBlock(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_slab_216");
    public static final Block BRAID_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_1");
    public static final Block BRAID_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_2");
    public static final Block BRAID_3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_3");
    public static final Block BRAID_4 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_4");
    public static final Block BRAID_5 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_5");
    public static final Block BRAID_6 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_6");
    public static final Block BRAID_7 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ACACIA_PLANKS)), "braid_7");
    public static final Block BRAID_101 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_101");
    public static final Block BRAID_102 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_102");
    public static final Block BRAID_103 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_103");
    public static final Block BRAID_104 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_104");
    public static final Block BRAID_105 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "braid_105");
    public static final Block BRAID_106 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.QUARTZ_BLOCK)), "braid_106");
    public static final Block BRAID_107 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PACKED_ICE)), "braid_107");
    public static final Block BRAID_108 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.GLOWSTONE).dropsLike(Blocks.GLOWSTONE)), "braid_108");
    public static final Block BRAID_109 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.END_STONE)), "braid_109");
    public static final Block BRAID_110 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DEEPSLATE)), "braid_110");
    public static final Block BRAID_111 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COBBLESTONE)), "braid_111");
    public static final Block BRAID_112 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COAL_BLOCK)), "braid_112");
    public static final Block BRAID_113 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PRISMARINE)), "braid_113");
    public static final Block BRAID_114 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.REDSTONE_BLOCK)), "braid_114");
    public static final Block BRAID_115 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "braid_115");
    public static final Block BRAID_116 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "braid_116");
    public static final Block BRAID_117 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "braid_117");
    public static final Block BRAID_201 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_201");
    public static final Block BRAID_202 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_202");
    public static final Block BRAID_203 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_203");
    public static final Block BRAID_204 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_204");
    public static final Block BRAID_205 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_205");
    public static final Block BRAID_206 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_206");
    public static final Block BRAID_207 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_207");
    public static final Block BRAID_208 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_208");
    public static final Block BRAID_209 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_209");
    public static final Block BRAID_210 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_210");
    public static final Block BRAID_211 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_211");
    public static final Block BRAID_212 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_212");
    public static final Block BRAID_213 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_213");
    public static final Block BRAID_214 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_214");
    public static final Block BRAID_215 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_215");
    public static final Block BRAID_216 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "braid_216");

    public static final Block BRICK_IRON = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.GOLD_BLOCK)), "brick_gold");
    public static final Block BRICK_GOLD = registerBlock(new PillarBlock(PillarBlock.Settings.copy(Blocks.IRON_BLOCK)), "brick_iron");
    public static final Block BRICK_DIRT_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COARSE_DIRT).strength(1)), "brick_dirt_1");
    public static final Block BRICK_DIRT_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COARSE_DIRT).strength(1)), "brick_dirt_2");
    public static final Block BRICK_DIRT_3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COARSE_DIRT).strength(1)), "brick_dirt_3");

    public static final Block CHAOTIC_1_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_1_1");
    public static final Block CHAOTIC_1_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_1_2");
    public static final Block CHAOTIC_1_3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_1_3");
    public static final Block CHAOTIC_1_4 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_1_4");
    public static final Block CHAOTIC_1_5 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_1_5");
    public static final Block CHAOTIC_1_6 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.QUARTZ_BLOCK)), "chaotic_1_6");
    public static final Block CHAOTIC_1_7 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PACKED_ICE)), "chaotic_1_7");
    public static final Block CHAOTIC_1_8 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.END_STONE)), "chaotic_1_8");
    public static final Block CHAOTIC_1_9 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DEEPSLATE)), "chaotic_1_9");
    public static final Block CHAOTIC_1_10 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COBBLESTONE)), "chaotic_1_10");
    public static final Block CHAOTIC_1_11 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COAL_BLOCK)), "chaotic_1_11");
    public static final Block CHAOTIC_1_12 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PRISMARINE)), "chaotic_1_12");
    public static final Block CHAOTIC_1_13 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "chaotic_1_13");
    public static final Block CHAOTIC_1_14 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "chaotic_1_14");
    public static final Block CHAOTIC_1_15 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "chaotic_1_15");
    public static final Block CHAOTIC_1_101 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_101");
    public static final Block CHAOTIC_1_102 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_102");
    public static final Block CHAOTIC_1_103 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_103");
    public static final Block CHAOTIC_1_104 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_104");
    public static final Block CHAOTIC_1_105 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_105");
    public static final Block CHAOTIC_1_106 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_106");
    public static final Block CHAOTIC_1_107 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_107");
    public static final Block CHAOTIC_1_108 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_108");
    public static final Block CHAOTIC_1_109 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_109");
    public static final Block CHAOTIC_1_110 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_110");
    public static final Block CHAOTIC_1_111 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_111");
    public static final Block CHAOTIC_1_112 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_112");
    public static final Block CHAOTIC_1_113 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_113");
    public static final Block CHAOTIC_1_114 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_114");
    public static final Block CHAOTIC_1_115 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_115");
    public static final Block CHAOTIC_1_116 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_1_116");
    public static final Block CHAOTIC_2_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_2_1");
    public static final Block CHAOTIC_2_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_2_2");
    public static final Block CHAOTIC_2_3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_2_3");
    public static final Block CHAOTIC_2_4 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_2_4");
    public static final Block CHAOTIC_2_5 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_2_5");
    public static final Block CHAOTIC_2_6 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.QUARTZ_BLOCK)), "chaotic_2_6");
    public static final Block CHAOTIC_2_7 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PACKED_ICE)), "chaotic_2_7");
    public static final Block CHAOTIC_2_8 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.END_STONE)), "chaotic_2_8");
    public static final Block CHAOTIC_2_9 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DEEPSLATE)), "chaotic_2_9");
    public static final Block CHAOTIC_2_10 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COBBLESTONE)), "chaotic_2_10");
    public static final Block CHAOTIC_2_11 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COAL_BLOCK)), "chaotic_2_11");
    public static final Block CHAOTIC_2_12 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PRISMARINE)), "chaotic_2_12");
    public static final Block CHAOTIC_2_13 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "chaotic_2_13");
    public static final Block CHAOTIC_2_14 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "chaotic_2_14");
    public static final Block CHAOTIC_2_15 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "chaotic_2_15");
    public static final Block CHAOTIC_2_16 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.GLOWSTONE).dropsLike(Blocks.GLOWSTONE)), "chaotic_2_16");
    public static final Block CHAOTIC_2_17 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.REDSTONE_BLOCK)), "chaotic_2_17");
    public static final Block CHAOTIC_2_101 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_101");
    public static final Block CHAOTIC_2_102 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_102");
    public static final Block CHAOTIC_2_103 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_103");
    public static final Block CHAOTIC_2_104 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_104");
    public static final Block CHAOTIC_2_105 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_105");
    public static final Block CHAOTIC_2_106 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_106");
    public static final Block CHAOTIC_2_107 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_107");
    public static final Block CHAOTIC_2_108 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_108");
    public static final Block CHAOTIC_2_109 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_109");
    public static final Block CHAOTIC_2_110 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_110");
    public static final Block CHAOTIC_2_111 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_111");
    public static final Block CHAOTIC_2_112 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_112");
    public static final Block CHAOTIC_2_113 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_113");
    public static final Block CHAOTIC_2_114 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_114");
    public static final Block CHAOTIC_2_115 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_115");
    public static final Block CHAOTIC_2_116 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_2_116");
    public static final Block CHAOTIC_3_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_3_1");
    public static final Block CHAOTIC_3_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_3_2");
    public static final Block CHAOTIC_3_3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_3_3");
    public static final Block CHAOTIC_3_4 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_3_4");
    public static final Block CHAOTIC_3_5 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "chaotic_3_5");
    public static final Block CHAOTIC_3_6 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.QUARTZ_BLOCK)), "chaotic_3_6");
    public static final Block CHAOTIC_3_7 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PACKED_ICE)), "chaotic_3_7");
    public static final Block CHAOTIC_3_8 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.END_STONE)), "chaotic_3_8");
    public static final Block CHAOTIC_3_9 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DEEPSLATE)), "chaotic_3_9");
    public static final Block CHAOTIC_3_10 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COBBLESTONE)), "chaotic_3_10");
    public static final Block CHAOTIC_3_11 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COAL_BLOCK)), "chaotic_3_11");
    public static final Block CHAOTIC_3_12 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PRISMARINE)), "chaotic_3_12");
    public static final Block CHAOTIC_3_13 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "chaotic_3_13");
    public static final Block CHAOTIC_3_14 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "chaotic_3_14");
    public static final Block CHAOTIC_3_15 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "chaotic_3_15");
    public static final Block CHAOTIC_3_16 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.GLOWSTONE).dropsLike(Blocks.GLOWSTONE)), "chaotic_3_16");
    public static final Block CHAOTIC_3_17 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.REDSTONE_BLOCK)), "chaotic_3_17");
    public static final Block CHAOTIC_3_101 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_101");
    public static final Block CHAOTIC_3_102 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_102");
    public static final Block CHAOTIC_3_103 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_103");
    public static final Block CHAOTIC_3_104 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_104");
    public static final Block CHAOTIC_3_105 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_105");
    public static final Block CHAOTIC_3_106 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_106");
    public static final Block CHAOTIC_3_107 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_107");
    public static final Block CHAOTIC_3_108 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_108");
    public static final Block CHAOTIC_3_109 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_109");
    public static final Block CHAOTIC_3_110 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_110");
    public static final Block CHAOTIC_3_111 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_111");
    public static final Block CHAOTIC_3_112 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_112");
    public static final Block CHAOTIC_3_113 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_113");
    public static final Block CHAOTIC_3_114 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_114");
    public static final Block CHAOTIC_3_115 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_115");
    public static final Block CHAOTIC_3_116 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "chaotic_3_116");

    public static final Block FONAR_STOLB = registerBlock(new Fonar(AbstractBlock.Settings.create().strength(0.5f, 5).sounds(BlockSoundGroup.METAL).noBlockBreakParticles()), "fonar_stolb");
    public static final Block FONAR_BASE = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB)), "fonar_base");
    public static final Block FONAR_STOLB2 = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB)), "fonar_stolb2");
    public static final Block FONAR_LAMP20 = registerBlock(new Fonar2(AbstractBlock.Settings.copy(FONAR_STOLB).luminance(state -> 15)), "fonar_lamp20");
    public static final Block FONAR_LAMP1 = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB).luminance(state -> 8)), "fonar_lamp1");
    public static final Block FONAR_LAMP2 = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB).luminance(state -> 11)), "fonar_lamp2");
    public static final Block FONAR_LAMP3 = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB).luminance(state -> 13)), "fonar_lamp3");
    public static final Block FONAR_LAMP4 = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB).luminance(state -> 15)), "fonar_lamp4");
    public static final Block FONAR_LAMP11 = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB).luminance(state -> 5)), "fonar_lamp11");
    public static final Block FONAR_LAMP12 = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB).luminance(state -> 7)), "fonar_lamp12");
    public static final Block FONAR_LAMP13 = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB).luminance(state -> 8)), "fonar_lamp13");
    public static final Block FONAR_LAMP14 = registerBlock(new Fonar(AbstractBlock.Settings.copy(FONAR_STOLB).luminance(state -> 10)), "fonar_lamp14");

    public static final Block CIRCULAR_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "circular_1");
    public static final Block CIRCULAR_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "circular_2");
    public static final Block CIRCULAR_3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "circular_3");
    public static final Block CIRCULAR_4 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "circular_4");
    public static final Block CIRCULAR_5 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.ANDESITE)), "circular_5");
    public static final Block CIRCULAR_6 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.QUARTZ_BLOCK)), "circular_6");
    public static final Block CIRCULAR_7 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PACKED_ICE)), "circular_7");
    public static final Block CIRCULAR_8 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.END_STONE)), "circular_8");
    public static final Block CIRCULAR_9 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DEEPSLATE)), "circular_9");
    public static final Block CIRCULAR_10 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COBBLESTONE)), "circular_10");
    public static final Block CIRCULAR_11 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.COAL_BLOCK)), "circular_11");
    public static final Block CIRCULAR_12 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.PRISMARINE)), "circular_12");
    public static final Block CIRCULAR_13 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "circular_13");
    public static final Block CIRCULAR_14 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SANDSTONE)), "circular_14");
    public static final Block CIRCULAR_15 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BRICKS)), "circular_15");
    public static final Block CIRCULAR_16 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.GLOWSTONE).dropsLike(Blocks.GLOWSTONE)), "circular_16");
    public static final Block CIRCULAR_17 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.REDSTONE_BLOCK)), "circular_17");
    public static final Block CIRCULAR_18 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.EMERALD_BLOCK)), "circular_18");
    public static final Block CIRCULAR_101 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_101");
    public static final Block CIRCULAR_102 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_102");
    public static final Block CIRCULAR_103 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_103");
    public static final Block CIRCULAR_104 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_104");
    public static final Block CIRCULAR_105 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_105");
    public static final Block CIRCULAR_106 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_106");
    public static final Block CIRCULAR_107 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_107");
    public static final Block CIRCULAR_108 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_108");
    public static final Block CIRCULAR_109 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_109");
    public static final Block CIRCULAR_110 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_110");
    public static final Block CIRCULAR_111 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_111");
    public static final Block CIRCULAR_112 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_112");
    public static final Block CIRCULAR_113 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_113");
    public static final Block CIRCULAR_114 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_114");
    public static final Block CIRCULAR_115 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_115");
    public static final Block CIRCULAR_116 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.BLACK_CONCRETE)), "circular_116");

    public static final Block CELL_1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DIAMOND_BLOCK)), "cell_1");
    public static final Block CELL_2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DIRT)), "cell_2");
    public static final Block CELL_3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.EMERALD_BLOCK)), "cell_3");
    public static final Block CELL_4 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.EMERALD_BLOCK)), "cell_4");
    public static final Block CELL_5 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.LAPIS_BLOCK)), "cell_5");

    public static final Block PRESENT_SMALL = registerBlock(new Present(AbstractBlock.Settings.copy(Blocks.DIRT).sounds(BlockSoundGroup.SNOW)), "present_small");
    public static final Block PRESENT_MEDIUM = registerBlock(new Present(AbstractBlock.Settings.copy(Blocks.DIRT).sounds(BlockSoundGroup.SNOW)), "present_medium");
    public static final Block PRESENT_BIG = registerBlock(new Present(AbstractBlock.Settings.copy(Blocks.DIRT).sounds(BlockSoundGroup.SNOW)), "present_big");
    public static final Block PRESENT_INSTRUMENT = registerBlock(new Present(AbstractBlock.Settings.copy(Blocks.DIRT).sounds(BlockSoundGroup.SNOW)), "present_instrument");
    public static final Block PRESENT_WINTER = registerBlock(new Present(AbstractBlock.Settings.copy(Blocks.DIRT).sounds(BlockSoundGroup.SNOW)), "present_winter");
    public static final Block ELKA = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.OAK_WOOD).luminance(state -> 15).nonOpaque()), "elka");
    public static final Block LEDENETS = registerBlock(new Ledenets(), "ledenets", "abc");
    public static final Block LEDENETS1 = registerBlock(new Ledenets(), "ledenets1", "abc1");
    public static final Block LEDENETS2 = registerBlock(new Ledenets(), "ledenets2", "abc");
    public static final Block SNOWMAN = registerBlock(new Snowman(), "snowman");
    public static final Block WINTER_STONE1 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_1");
    public static final Block WINTER_STONE2 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_2");
    public static final Block WINTER_STONE3 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_3");
    public static final Block WINTER_STONE4 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_4");
    public static final Block WINTER_STONE5 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_5");
    public static final Block WINTER_STONE6 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_6");
    public static final Block WINTER_STONE7 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_7");
    public static final Block WINTER_STONE8 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_8");
    public static final Block WINTER_STONE9 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_9");
    public static final Block WINTER_STONE10 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_10");
    public static final Block WINTER_STONE11 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_11");
    public static final Block WINTER_STONE12 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_12");
    public static final Block WINTER_STONE13 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_13");
    public static final Block WINTER_STONE14 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_14");
    public static final Block WINTER_STONE15 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_15");
    public static final Block WINTER_STONE16 = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SMOOTH_STONE)), "winter_stone_16");
    public static final Block SUGAR_BLOCK_WHITE = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DIRT)), "sugar_block_white");
    public static final Block SUGAR_BLOCK_YELLOW = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DIRT)), "sugar_block_yellow");
    public static final Block SUGAR_BLOCK_RED = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DIRT)), "sugar_block_red");
    public static final Block SUGAR_BLOCK_BROWN = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.DIRT)), "sugar_block_brown");

    public static final Block LAMP = registerBlock(new LampBlock(), "lamp");
    public static final Block BICYCLE = registerBlock(new Bicycle(), "bicycle");
    public static final Block PIX = registerBlock(new Block(AbstractBlock.Settings.copy(Blocks.SNOW_BLOCK).nonOpaque().noBlockBreakParticles().sounds(BlockSoundGroup.GLASS).strength(3, 9999999)), "pix");
    public static final Block BATUT = registerBlock(new Batut(AbstractBlock.Settings.copy(Blocks.SNOW_BLOCK).nonOpaque().noBlockBreakParticles().strength(-1, 9999), (byte) 0), "batut");

    private static Block registerBlock(Block block, String name, String method) {
        return Registry.register(Registries.BLOCK, Identifier.of(Radik.MOD_ID, name), block);
    }

    private static Block registerBlock(Block block, String name) {
        registerBlockItem(name, block);
        return Registry.register(Registries.BLOCK, Identifier.of(Radik.MOD_ID, name), block);
    }

    private static void registerBlockItem(@NotNull String name, Block block) {
        switch (name) {
            case "batut": Registry.register(Registries.ITEM, Identifier.of(Radik.MOD_ID, name), new BlockItem(block, new Item.Settings().maxCount(1))); break;
            default: Registry.register(Registries.ITEM, Identifier.of(Radik.MOD_ID, name), new BlockItem(block, new Item.Settings()));
        }
    }

    @RadikCore
    public static void initialize() {
        Radik.LOGGER.info("BLOCK INCLUDED");
    }
}